var config1={
    'chart_width':600,
    'chart_height':300,
    'bar_margin':25,
    'background_color':'white',
    'line_color':'blue',
    'bar_color':'black',
    'pad':[100,340,80,140],
    'popup_text_width':100,
	'popup_background':'#123456',
	// controlled by viewer
	'average_line_by':'ow',
	'line_by':'points',
    'show_breakdown':true,
    'show_bar':true,
    'show_line':true,
	'top_title':"No. of Checkins Per Company Over a Day group by Store",
	'left_title':"No. of Checkins (bars) ",
	'right_title':"Points Redeemed (lines) ",
	'circle_title':"Points Redeemed (lines) ",
	't_domain':['hour', 'day', 'week', 'month'],
	't_by': 'day',
	'unique_color': 'Olive',
};
var config2={
    'chart_width':600,
    'chart_height':300,
    'bar_margin':25,
    'background_color':'white',
    'line_color':'blue',
    'bar_color':'black',
    'pad':[100,340,80,140],
    'popup_text_width':100,
	'popup_background':'#123456',
	// controlled by viewer
	'average_line_by':'ow',
	'line_by':'points',
    'show_breakdown':true,
    'show_bar':true,
    'show_line':true,
	'top_title':"No. of Checkins Per Store Over a Day group by Activities",
	'left_title':"No. of Checkins (bars) ",
	'right_title':"Points Redeemed (lines) ",
	'circle_title':"Points Redeemed (lines) ",
	't_domain':['hour', 'day', 'week', 'month'],
	't_by': 'day',
	'unique_color': 'Olive',
};
